version: '1.0.{build}'
image: Visual Studio 2019
platform: Any CPU
configuration:
  - Debug
  - Release
build:
  verbosity: minimal
before_build:
  - appveyor-retry dotnet restore -v Minimal "H.NET.Core"
  - appveyor-retry dotnet restore -v Minimal "H.NET.Tests"
build_script:
  - dotnet build "H.NET.Core" -c %CONFIGURATION%
  - dotnet build "H.NET.Tests" -c %CONFIGURATION%
test_script:
  - dotnet test "H.NET.Tests" -c %CONFIGURATION%
on_success:
 - ps: >-
      if ($env:Configuration -eq "Release") {
        choco install opencover.portable
        choco install codecov
        OpenCover.Console.exe -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full H.NET.Tests" -hideskipped:File -output:coverage.xml -oldStyle -filter:"+[H.NET*]* -[H.NET.Tests*]*" -register:user
        codecov -f "coverage.xml" -t 859daacd-d023-4e20-813e-e5baf7f1911d
      }